// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyPlus.Infrastructure.Data;

#nullable disable

namespace SkyPlus.Infrastructure.Migrations
{
    [DbContext(typeof(SkyPlusDbContext))]
    [Migration("20260907115337_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SkyPlus.Domain.Entities.Aeronave", b =>
                {
                    b.Property<int>("IdAeronave")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aeronave");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAeronave"));

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("modelo");

                    b.HasKey("IdAeronave");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("aeronave", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Asiento", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asiento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado");

                    b.Property<int>("Fila")
                        .HasColumnType("int")
                        .HasColumnName("fila");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("int")
                        .HasColumnName("id_vuelo");

                    b.Property<string>("Letra")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("letra");

                    b.HasKey("IdAsiento");

                    b.HasIndex("IdVuelo", "Fila", "Letra")
                        .IsUnique();

                    b.ToTable("asiento", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.CheckIn", b =>
                {
                    b.Property<int>("IdCheckin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_checkin");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCheckin"));

                    b.Property<string>("BoardingPass")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("boarding_pass");

                    b.Property<string>("CodigoQr")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codigo_qr");

                    b.Property<DateTime>("FechaCheckin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_checkin");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdUsuarioAgente")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_agente");

                    b.HasKey("IdCheckin");

                    b.HasIndex("IdReserva")
                        .IsUnique();

                    b.HasIndex("IdUsuarioAgente");

                    b.ToTable("checkin", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.EquipajeReserva", b =>
                {
                    b.Property<int>("IdEquipajeReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_equipaje_reserva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEquipajeReserva"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdTipoEquipaje")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_equipaje");

                    b.Property<decimal>("PesoKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("peso_kg");

                    b.HasKey("IdEquipajeReserva");

                    b.HasIndex("IdReserva");

                    b.HasIndex("IdTipoEquipaje");

                    b.ToTable("equipaje_reserva", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Lugar", b =>
                {
                    b.Property<int>("IdLugar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_lugar");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdLugar"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoIata")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_iata");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pais");

                    b.HasKey("IdLugar");

                    b.HasIndex("CodigoIata")
                        .IsUnique();

                    b.ToTable("lugar", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_pago");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    b.Property<int>("IdUsuarioAgente")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_agente");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metodo_pago");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdPago");

                    b.HasIndex("IdReserva")
                        .IsUnique();

                    b.HasIndex("IdUsuarioAgente");

                    b.ToTable("pago", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Pasajero", b =>
                {
                    b.Property<int>("IdPasajero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pasajero");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPasajero"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("documento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.HasKey("IdPasajero");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("pasajero", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Reembolso", b =>
                {
                    b.Property<int>("IdReembolso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reembolso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReembolso"));

                    b.Property<DateTime>("FechaReembolso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_reembolso");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<int>("IdUsuarioAgente")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_agente");

                    b.Property<decimal>("MontoReembolsado")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("monto_reembolsado");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("motivo");

                    b.HasKey("IdReembolso");

                    b.HasIndex("IdPago")
                        .IsUnique();

                    b.HasIndex("IdUsuarioAgente");

                    b.ToTable("reembolso", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("CodigoReserva")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codigo_reserva");

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_reserva");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_cancelacion");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_reserva");

                    b.Property<int>("IdAsiento")
                        .HasColumnType("int")
                        .HasColumnName("id_asiento");

                    b.Property<int>("IdPasajero")
                        .HasColumnType("int")
                        .HasColumnName("id_pasajero");

                    b.Property<int>("IdUsuarioAgente")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_agente");

                    b.Property<int>("IdVuelo")
                        .HasColumnType("int")
                        .HasColumnName("id_vuelo");

                    b.Property<decimal>("TarifaBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarifa_base");

                    b.HasKey("IdReserva");

                    b.HasIndex("CodigoReserva")
                        .IsUnique();

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdPasajero");

                    b.HasIndex("IdUsuarioAgente");

                    b.HasIndex("IdVuelo");

                    b.ToTable("reserva", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.TipoEquipaje", b =>
                {
                    b.Property<int>("IdTipoEquipaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_equipaje");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoEquipaje"));

                    b.Property<decimal>("CostoAdicional")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("costo_adicional");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("LimiteKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("limite_kg");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoEquipaje");

                    b.ToTable("tipo_equipaje", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("apellido");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("EmailCorporativo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email_corporativo");

                    b.Property<string>("EstadoCuenta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_cuenta");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UltimaSesion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultima_sesion");

                    b.HasKey("IdUsuario");

                    b.HasIndex("EmailCorporativo")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Vuelo", b =>
                {
                    b.Property<int>("IdVuelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vuelo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVuelo"));

                    b.Property<string>("EstadoVuelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_vuelo");

                    b.Property<int>("IdAeronave")
                        .HasColumnType("int")
                        .HasColumnName("id_aeronave");

                    b.Property<int>("IdLugarDestino")
                        .HasColumnType("int")
                        .HasColumnName("id_lugar_destino");

                    b.Property<int>("IdLugarOrigen")
                        .HasColumnType("int")
                        .HasColumnName("id_lugar_origen");

                    b.Property<int>("IdUsuarioOperador")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_operador");

                    b.Property<DateTime>("Llegada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("llegada");

                    b.Property<string>("NumeroVuelo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_vuelo");

                    b.Property<DateTime>("Salida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("salida");

                    b.Property<decimal>("Tarifa")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("tarifa");

                    b.HasKey("IdVuelo");

                    b.HasIndex("IdAeronave");

                    b.HasIndex("IdLugarDestino");

                    b.HasIndex("IdLugarOrigen");

                    b.HasIndex("IdUsuarioOperador");

                    b.ToTable("vuelo", (string)null);
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Asiento", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.CheckIn", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Usuario", "UsuarioAgente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioAgente");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.EquipajeReserva", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.TipoEquipaje", "TipoEquipaje")
                        .WithMany()
                        .HasForeignKey("IdTipoEquipaje")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("TipoEquipaje");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Pago", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Usuario", "UsuarioAgente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("UsuarioAgente");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Reembolso", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Pago", "Pago")
                        .WithMany()
                        .HasForeignKey("IdPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Usuario", "UsuarioAgente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pago");

                    b.Navigation("UsuarioAgente");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Asiento", "Asiento")
                        .WithMany()
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Pasajero", "Pasajero")
                        .WithMany()
                        .HasForeignKey("IdPasajero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Usuario", "UsuarioAgente")
                        .WithMany()
                        .HasForeignKey("IdUsuarioAgente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Vuelo", "Vuelo")
                        .WithMany()
                        .HasForeignKey("IdVuelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Pasajero");

                    b.Navigation("UsuarioAgente");

                    b.Navigation("Vuelo");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SkyPlus.Domain.Entities.Vuelo", b =>
                {
                    b.HasOne("SkyPlus.Domain.Entities.Aeronave", "Aeronave")
                        .WithMany()
                        .HasForeignKey("IdAeronave")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Lugar", "LugarDestino")
                        .WithMany()
                        .HasForeignKey("IdLugarDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Lugar", "LugarOrigen")
                        .WithMany()
                        .HasForeignKey("IdLugarOrigen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyPlus.Domain.Entities.Usuario", "UsuarioOperador")
                        .WithMany()
                        .HasForeignKey("IdUsuarioOperador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aeronave");

                    b.Navigation("LugarDestino");

                    b.Navigation("LugarOrigen");

                    b.Navigation("UsuarioOperador");
                });
#pragma warning restore 612, 618
        }
    }
}
